import requests
import urllib.parse
import io
import discord
from discord.ext import commands


class LatexCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def latex(self, ctx, *, arguments):
        """Parses LaTeX and returns an image with the formatted result"""
        latex = urllib.parse.quote(arguments)
        req_url = (
            "https://latex.codecogs.com/png.latex?\\dpi{300}&space;\\bg_black&space;%s"
            % (latex)
        )
        embed = discord.Embed(title="LaTeX output", color=0x0539F5)
        embed.add_field(name="Input:", value="`%s`" % (arguments), inline=False)
        embed.set_image(url=req_url)
        embed.set_footer(text="Generated by codecogs.com")
        await ctx.send(embed=embed)
        # r = requests.get(req_url)
        # b = io.BytesIO(r.content)
        # await ctx.send(file=discord.File(b, "LaTeX.png"))


def setup(bot):
    bot.add_cog(LatexCog(bot))
